name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: ":fire: Hotfixes"
    labels:
      - "Type: Hotfix"
      - "Priority: Critical"
  - title: ":sparkles:  New features"
    labels:
      - "Type: Feature"
      - "Type: Release"
  - title: ":page_facing_up: Documentation"
      - "Type: Documentation"
  - title: ":nail_care: Enhancements"
      - "Type: Enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "Type: Bug"
  - title: ":robort: Dev environment"
    label: "Type: Maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes
  $CHANGES
  $CONTRIBUTORS
